#!/usr/bin/env python
"""
convert_gii_to_obj.py

Convert hippocampal surface meshes from GIFTI (.gii) to Wavefront OBJ (.obj)
for use in Unity and other 3D engines.

Requirements:
    pip install nibabel numpy

Usage (single file):
    python convert_gii_to_obj.py \
        --input ../meshes/gii/human_hippo.L.surf.gii \
        --output ../meshes/obj/human_hippo_L.obj

Usage (batch from directory):
    python convert_gii_to_obj.py \
        --batch ../meshes/gii \
        --output-dir ../meshes/obj

Notes:
    - This script assumes a standard surface GIFTI file with:
        * one data array for vertex coordinates (Nx3)
        * one data array for triangle indices (Mx3)
    - It writes a simple OBJ with:
        * 'v x y z' lines for vertices
        * 'f i j k' lines (1-based indices) for faces
    - Normals/UVs/materials are intentionally omitted for minimal interoperability.
"""

import argparse
import os
import sys
from typing import Tuple

import nibabel as nib
import numpy as np


def load_gifti_mesh(path: str) -> Tuple[np.ndarray, np.ndarray]:
    """Load a surface mesh from a GIFTI file.

    Parameters
    ----------
    path : str
        Path to .gii surface file.

    Returns
    -------
    vertices : (N, 3) float32 array
    faces : (M, 3) int32 array (0-based indices)
    """
    gii = nib.load(path)
    darrays = gii.darrays
    if len(darrays) < 2:
        raise ValueError(f"Expected at least 2 data arrays (coords + faces) in {path}")

    # Heuristic: first array = coords, second = faces
    coords = np.asanyarray(darrays[0].data, dtype=np.float32)
    faces = np.asanyarray(darrays[1].data, dtype=np.int32)

    if coords.ndim != 2 or coords.shape[1] != 3:
        raise ValueError(f"Vertex array must be (N,3), got {coords.shape} in {path}")
    if faces.ndim != 2 or faces.shape[1] != 3:
        raise ValueError(f"Face array must be (M,3), got {faces.shape} in {path}")

    return coords, faces


def write_obj(path: str, vertices: np.ndarray, faces: np.ndarray) -> None:
    """Write a simple OBJ file with vertices and faces.

    Parameters
    ----------
    path : str
        Output OBJ filepath.
    vertices : (N, 3) array
    faces : (M, 3) array, 0-based indices
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        f.write("# OBJ file generated by convert_gii_to_obj.py\n")
        f.write("# Vertices: {}\n".format(vertices.shape[0]))
        f.write("# Faces: {}\n".format(faces.shape[0]))

        # Write vertices
        for v in vertices:
            f.write("v {:.6f} {:.6f} {:.6f}\n".format(*v))

        # Write faces (OBJ is 1-based indexing)
        for tri in faces:
            i, j, k = tri + 1
            f.write(f"f {i} {j} {k}\n")


def convert_single(input_path: str, output_path: str) -> None:
    print(f"[INFO] Converting: {input_path} -> {output_path}")
    vertices, faces = load_gifti_mesh(input_path)
    write_obj(output_path, vertices, faces)
    print("[INFO] Done.")


def convert_batch(input_dir: str, output_dir: str, suffix: str = ".gii") -> None:
    if not os.path.isdir(input_dir):
        raise FileNotFoundError(f"Input directory does not exist: {input_dir}")

    files = [
        f for f in os.listdir(input_dir)
        if f.lower().endswith(suffix.lower())
    ]
    if not files:
        print(f"[WARN] No *{suffix} files found in {input_dir}")
        return

    os.makedirs(output_dir, exist_ok=True)
    for fname in files:
        in_path = os.path.join(input_dir, fname)
        base, _ = os.path.splitext(fname)
        out_name = base + ".obj"
        out_path = os.path.join(output_dir, out_name)
        convert_single(in_path, out_path)


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert hippocampal surface meshes from GIFTI (.gii) to OBJ (.obj)."
    )

    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--input",
        type=str,
        help="Single input GIFTI surface file (.gii).",
    )
    group.add_argument(
        "--batch",
        type=str,
        help="Directory containing GIFTI surface files to convert in batch.",
    )

    parser.add_argument(
        "--output",
        type=str,
        help="Output OBJ file (for single-file mode).",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        help="Output directory for batch mode.",
    )

    return parser.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)

    if args.input:
        if not args.output:
            print("[ERROR] --output is required for single-file mode.", file=sys.stderr)
            return 1
        convert_single(args.input, args.output)
        return 0

    # Batch mode
    if not args.output_dir:
        print("[ERROR] --output-dir is required for batch mode (--batch).", file=sys.stderr)
        return 1

    convert_batch(args.batch, args.output_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

